version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: cinema_user
      POSTGRES_PASSWORD: cinema_pass
      POSTGRES_DB: cinema_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgres/data

  keycloak:
    image: quay.io/keycloak/keycloak:17.0.1
    environment:
      KEYKLOAK_ADMIN: admin
      KEYKLOAK_ADMIN_PASSWORD: admin
    command: start-dev
    ports:
      - "8081:8080"

volumes:
  pgdata:
